b = float(input("Số tiền vnđ là"))
a = float("0.000042")
print("Quy đổi sang USD ta được:", b*a)
c = float(input("Số tiền vnđ là"))
d = float("0.000039")
print("Quy đổi sang Euro ta được:", c*d)
e = float(input("Số tiền vnđ là"))
f = float("0.0060")
print("Quy đổi sang Yên ta được:", e*f)
g = float(input("Số tiền vnđ là"))
h = float("0.00030")
print("Quy đổi sang Nhân dân tệ ta được:", g*h)
i = float(input("Số tiền vnđ là"))
k = float("0.054")
print("Quy đổi sang tiền Hàn ta được:", i*k)
l = float(input("Số tiền vnđ là"))
m = float("0.0015")
print("Quy đổi sang tiền Thái ta được:", l*m)
n = float(input("Số tiền vnđ là"))
o = float("0.0013")
print("Quy đổi sang tiền Đài Loan ta được:", n*o)
c = float(input("Bán kính của hình tròn là:"))
d = float("3.14")
e = 2
print("Chu vi hình tròn là:", e * c * d)
print("Diện tích hình tròn là:", d * (c**e))
f = float(input("Thời gian về đích vận động viên thứ 1 là:"))
g = float(input("Thời gian về đích vận động viên thứ 2 là:"))
h = float(input("Thời gian về đích vận động viên thứ 3 là:"))
i = 3
print("thời gian trung bình các vận động viên về đích là", (f + g + h) / i)